### ISSUE TITLE
LF not translated to CRLF in Windows console

### ISSUE THREAD

**Issue by mircolino** [srs/gradle-gulp-plugin#3]
When executing gradle in a Windows console the gulp task output is misaligned. Running gradle with --console plain fixes the problem:

---

``` javascript
c:\dev\prj>gradle gulp_js
:gulp_js
[23:19:03] Using gulpfile c:\dev\prj\gulpfile.js
                                                 [23:19:03] Starting 'js'...
                                                                             [23:19:03] Finished 'js' after 16 ms

BUILD SUCCESSFUL

Total time: 3.749 secs
```

---

``` javascript
c:\dev\prj>gradle gulp_js --console plain
:gulp_js
[23:19:19] Using gulpfile c:\dev\prj\gulpfile.js
[23:19:19] Starting 'js'...
[23:19:19] Finished 'js' after 14 ms

BUILD SUCCESSFUL

Total time: 3.639 secs
```

---

**Comment by srs** [comment]
Thanks for reporting. Will schedule this fix for next version (0.10) together with the same fix for Grunt and Node.

**Comment by evpaassen** [comment]
I'm experiencing this too. Will wait for 0.10.

**Comment by srs** [comment]
Think this is fixed by #6. Will test this further after 0.10 release if that fix does not fix your problem.

**Comment by evpaassen** [comment]
Unfortunately, this issue still exists in 0.10.

**Comment by brian428** [comment]
Yep just a note that this also happens for me (just to let Sten know that it's not just one person who's seeing this).
